import { Component,OnInit } from '@angular/core';
import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { SocialUser } from 'angularx-social-login';
import { User } from '../user/user.model';
import { Router } from "@angular/router";

@Component({
	selector: 'app-menu',
	templateUrl: './menu.component.html',
	styleUrls: ['./menu.component.css'] 
})
export class MenuComponent implements OnInit{
	
	usuariologado: User;
	susuariologado: SocialUser;
	admin: boolean;
	

	isHandset$: Observable<boolean> = this.breakpointObserver.observe(Breakpoints.Handset)
		.pipe(
			map(result => result.matches)
		);

	constructor(private breakpointObserver: BreakpointObserver, private router: Router) {
	
		
	}

	ngOnInit() {
		
		this.usuariologado = {"id":62,"token":null,"provider":"GOOGLE","name":"Moyzes Braz","email":"moyzes@gmail.com","adress":null,"zipcode":null,"city":null,"state":null,"country":null,"lastlocation":null,"superuser":true,"photos":[{"id":63,"user_id":62,"photo":"/9j/4AAQSkZJRgABAQAAAQABAAD/4QAqRXhpZgAASUkqAAgAAAABADEBAgAHAAAAGgAAAAAAAABHb29nbGUAAP/bAIQAAwICDg0ICQgICgkKCA8NCAoKCgoICQoKCgsKCggICAkICAoJCwoKCggICggICgsKCAsKCQsIDgsNCggOCAoNCAEDBAQCAgIJAgIJCAICAggICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI/8AAEQgAYABgAwERAAIRAQMRAf/EAB4AAAEEAwADAAAAAAAAAAAAAAcDBQYIAgQJAAEK/8QAOBAAAgECBAUCBAQFAwUAAAAAAQIDBBEAEhMhBQYHIjEIQSMyUWEUQnGBCTORofBSYtEVJXLB4f/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDpTTnbAKMcBizYBv4xxgRxmR/A8D3J9gPufr4UAsSACQAQ5q6uBmYLMAo2sts7Ej2zWCKAVt233zZiRgB8OtWa8SBn08gnjESkhnG+ZkBJOa4N/DABcwVsoHPppxFGjyg5htdTlDfltZVAQqB8ylLm4OW77hGOu3QqOtSOVJJ4pI2zI9NMY5UbcN5kWJj3MbSo6m4sgZVDgOeEcPqQkwqadxpOunK4KGaJmCtUR2ZHV4HYRzqyaU6sJEIyNmCdckc39xSqQBgQA1zpWNsrh1XKpftYaqoTY5XfcKBy4FxdcgQlRYZbXO1trEHcW2G/9cA/o2AaoW2wGTPgEnfAVa9ZHWgQwGlhf4g1NX/aDC583F7KSStwGBsWAuVDnl0758nrOPpFFKRSgxy1ADHIsFO4kLFdxmkRnjstmYTHOTlURgeKzqIaKSaSiVYYPLySAtqsyowCxkoZSQWeSXWTuQBmkO0IFPpT6uYWJEsTNPlQui2hmdTbTmhdnS+VbEpMzSFO8Nkly4A+cN6ixSpmp6gjbtSRWimW4zAXVkuq+SHBIuR2EHACbqr1BlSKtMMuozwaYZyXVBbvZXYZzcCR7uWA0B73UAKeSvUfaop1nJAdFVi9vBOk93ZWuElV4Jla+ZYVkyKXUoFhKTqUUqqZYWGmz5JUuNgpVo8ii7KrRZsqsWyquVS4ytgLWReMA0RNtgPTPgNeSXAcuPWfzSr1tYcriMSKrt4WSSIKagAnZgogZbFrafZ273Cpvpe4tJDxqOJLssiTRO673R1Ekct7XKlkjJVvYkWVr4C2PLfLCTySZyxKSKWR7EozISiAAb6cYVQGG+cdt3NwLXL/AEXjzLIVVm8g7H2IBuRc7EgWIupt9MAUuCcohFAW1hvfLud791/J+pJuxP08BpHlAO8ysoy3UD6BSHABHvcAKRa1gBY2wFO/UZyQ1KjvGNkkzqSNhHNcS337sswRvN1B2YXOAOHp35lWWGCokYFNJUbMQrE3aMgOBbUjYPIb22IsEuFUL+dP+a0qKVJojcdyHxcMhysGA8HwSLC1/AwC0bbYBKRsBqyvgOUP8RukMNfIucGJxKxjMioy60/4pJoAT8QxuXDhFMoAAIVXViG16PvTs9NKauuUBLEROWATuK3IDZctyNtrOLMCcxsBZ5r6ZRmuapj4pBTVDaasiCIpMiMGGrG0txMLlBJGwsrAGOTKmUDfy3wPKgAcye+Ykb39xa36/wCbA9pCbf2wGlSX1CfyEEG9vmVu21t+4MTfbx9yMAPfUNyOs3D5gBuEZttzsQ+3sblQDtvf7C4Ul6O9VjDTVNC0mW0kTwMScrd9pIiqksySZgwBBKdxszKAQ6lejim/7bJOt9OWVnUFswuqqjsvtY2C3BIbLmB7rACwr7YBF5MBqytgOfX8Uvo4z0q8Yh71RVinhsfyuGScEEECKPVVt91a5+UYAac59OuJVPCuHCv4wIYPw8cuSKNYIxGY1KvLNqAyuo7Scqhfyx3JJCu/M3RPh48cbRpTvfJrA3O5GQgG7XH8z5jbc3wBq6b9aavhNAZ45YOL8NQxiQiZop4AzaYBRlkVl1GTdZC1z3BVBICVP6+Jq+Oal4VQvHNp3M808SRwXITPIxNvmYBQDnc/KhtgBnwLgnHJJ2NPxqnMthdBWu9vp8L8MVB8nZR9sBN+UepHHIKk0fE6duIRsrWaIQ5wQpsY8zQq+5F1YLcHZie0gHfTj0nlr+ILSUrR3zLmASQqoYnSaYSRLcQxLIYyrOQIRuoBfAdy+Q+To6WkgoqZcsMahFH13LOx+8jlnb7scAhn2wCDvgNWSTAAf1bVavwetpGRGLxSx3eVI8hdGBdbnMSqm6gL3ntDL5wEL6T8ipW8s8Piq1SSVIfw88TKDpzRFo5YHQ5v5bACxuHUBgWVgSFdeoPpljE2pGhV0ASFVuFjAzFUiVcpVQS5ABABcm12OAhXA/T07V3DuDzZTHKWqqqKM2IpKeRH+Kb3yyTiOAKPlMwZb6bZQIHqP6LBOLUElFEkaVkVRQzKFVYjNBH+Jo3KgW1HRJYgx8CMfe4Qrp56Vb1kNTII9SMFdKWMyIWGbTkYXViVLZh3bkb6gwFr+mPIUlNTSo081UI4p3V5mEkpyxswQy2Ba2UBcxJ+rN5wEY/hZ8upFTTzrCHmlVLyoEI0oWkp4VErSC5CxZ2QC3x865g7HAdC4W/b/Pt/zgIoJNsAhLLgNKaowEC6u8mrV0FRSuqszI2TNewexyH9b+DYlScwsQMA1S9MaeWOKZleOo06dWnpqieklfTQIiyzUssTTKnhVlZ0Hi1r4CDc19PAt2/F1+Xft/E3uP8AyZC36nNf74B56P8ATWKLVrFjfWlRPiSzSzTOoLmMNLM7vkjzsUjBCJeyqqqoAZ9Q+myVVKY6pWbLJHNGYneOWN4nDxyxSIVZZIyMwKkf6dwxBCDUXTupyro10cn+6roFlZvpm/Cz0SX+toxe18AR+G9M53p3hra1dBlYSJQ0jUbyR2IeNp5KqqmRZFurNTvDMAeyWM74Alen7pAlBw6mpgqrMIqcTBCSglWNFl09lAXPe1kUZQAFQKAAKsZwENz7YDUnkwDbU1GAap6zAQyg4326SkXUyRH63Ryq7AH5h3HcefFjfARznLjCqDrukYtmN29vJ/oNzvb/ANgOOIdWwtVTvTSSmBFBkJLMmnmCXESmwYEmzMvyrs25DBJIvUKHqAA5jiW63tYXOxMmxAH0JKjewEuzYAjcrSixKkMvtY3tf2/Y3H2O3tgJ3wapuyxj3OX9Pc7XF7KCTbxbyMAS4ZMBuxtgIVqbYCP8y8yxwxvNUSRwxKCzSSusaKotdmdyAALj39wPcYConUv+JZw2BmSmFVXOMwvFFowhh4DSz5HIY+GjgkW3dc9uYKg9V/4jvEaltOhMXD4TbaBRLMb+z1EyEi31iiiO33wEs9EfqMYVlVw2tnkfWdqmCWWRnd5zlE8bvI12M4AlHgl1dsxMgOAtv1L5OaqZZIJzEVCgEKr7jKRkzgqvbe4C/nN7k4BOhWdIhHOKCZGzCRYqdoNt72u0pdiSWOaRLEm4PuCtVwVpBHFHQ0YQWCszy/Dt+YqqgeSTYOGk9yt7qEu6b8Dlp4njnEdyLhkvlLXBb4ZN1DMSQpZiL2zEYCvPWH14ii5o4dR0zqaGGYLxV7BgdYGGVEax3oo3MzZAGaZdIlcjhg6ScNrQyq6MrIQGVlIZWVgCrKwuGVgQQQbEG484B4hfAfP11A9W3EKlvj8SrmUC1kqmp0I8bwUmjET7X0ybDck3JARHjBvJMWvKTlJJJezgl2zsSxYgZC18wzeRcXBoknJ84DKBrb/t/cX/AOMAvS1rRyJIjFZFKujjyCDdWH72OAvh6XPVYs0yU9Y2Tts6ljbNm3khF7afhnXLmjLXJdELRhdr/oEUliMrHY3Ki4t43tfyPc72wDjHRJCjPIyRqLksTYAeSST4G1/2wFOfUt6tpkpagUfwU/lx1AbvZ3HaIBtuqkyOWF00rZbuDgOefL9GJalFmdgrNeR7F2sTdid7ksdrlgAWuzAXIDpZ6YfWuKSkpOGRRR1dGgmVRrtDVQASEhSJC8cqsrh41URqoIVXZd4wvn0s670tagNLNll7gaeYaU4ZdmXITZyvuYmdQCDffAfOcH+31/8An7DAJnAeDAZM2AUY3A/p/Tx/bb9sBjBOVYMpKsCCCCQQRuCCNwQdwR4wFj+jXq4khcLXNmUCyzI1RFL7D4mhKiOAABdoS25JY3NwN9R6l6epYqlRdjc2Jm1N1IfK880rpYG+aEqQFAFtxgKp9fuf/wARULHHtBHdY1Hj6FgPv9fJtck4CD8lA691BayyEgG1wFJtextc2F7Hz4OAPPO3PJrXaspIhOjM/ZUUdKrU6RR0wigcr8OeNXZl1iEmdVzOis0QwEu6fVZYBXEMEoETrp1NSqujMWjkEa2isG8/MEIvcMrYCnWA9l9re3sMB6wHgGAyWT29sB5bAY2wBX5YOjwCrnV8s9RUQxR2S50aHTlq+/8AKJJ6ygykDu0HSxDNlCMQov4dqp2XOc8SoAcwcKu5uLAMrlwQfyZdrdwYdOgA9Q7/ACiGS5vaxLIF3/Xfax28jATnkbmARUsMPyudSbMRY5ZRpsvkdpSMEebkDaxBAM78+sjDIb2zLl+x8sht4ky5XX/UA43d8wf/2Q=="}]}
		this.susuariologado = JSON.parse(localStorage.getItem("suserlogado"));


		if(!this.usuariologado || !this.admin) {

			this.router.navigate(['login']);

		}
		
		if(this.usuariologado!=null) {

			this.admin = this.usuariologado.superuser;
		}
		//console.log("Usuario logado:"+ JSON.stringify(this.usuariologado));
	}

}
